### PR TITLE
Angela's Changes - Steps for Preparation

### PR DESCRIPTION
**Pull request by aywang8**
## 🎯 Objective

Adding the preparation steps to the recipes.

## 🛠️ Changes made

Added preparation steps to breakfast + lunch + dinner.

## 👥 Who needs to review this Pull Request? 

@IntroToCode/fall20_codemates1

### CODE REVIEW

**Comment by caroline-tsoi** [comment]
Nice detailed steps.

**Review by sharpaero — COMMENTED** [review]
Looks good!

**Comment by les-chen** [comment]
looks great!

**Review by les-chen — APPROVED** [review]
looks great!

**Review by les-chen — APPROVED** [review]
looks great!

**Review by sharpaero — APPROVED** [review]
Looks Good

**Pull request closed without merging**
